[package]
name = "wot-replays-app"
version = "0.1.0"
authors = ["Sergei Tsaplin <s_tsaplin@wargaming.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
